import { openai } from "@ai-sdk/openai";
import { generateObject } from "ai";
import {
  calculateDailyStepsAdjustments,
  calculateStepsTarget,
  generateReasoning,
  generateTips,
} from "./recommendations";
import { StepsTargetSchemaForAI } from "./schemas";
import type {
  StepsGenerationOptions,
  StepsGenerationResult,
  StepsTarget,
} from "./types";

/**
 * Generate Steps Target - Strategy 1: Calculation-based (Fallback)
 * Pure calculation without AI, used as fallback or for testing
 */
export function generateStepsTargetCalculated(
  options: StepsGenerationOptions
): StepsGenerationResult {
  const { questionnaireData, workoutProgram } = options;

  const dailyStepsGoal = calculateStepsTarget(questionnaireData);
  const reasoning = generateReasoning(questionnaireData, dailyStepsGoal);
  const tips = generateTips(questionnaireData);

  // Calculate daily adjustments if workout program is available
  const dailyAdjustments = workoutProgram
    ? calculateDailyStepsAdjustments(workoutProgram, dailyStepsGoal)
    : undefined;

  const target: StepsTarget = {
    baseline: {
      dailyStepsGoal,
      weeklyTarget: dailyStepsGoal * 7,
    },
    dailyAdjustments,
    reasoning,
    tips,
  };

  return {
    target,
    metadata: {
      calculationMethod: "rule-based",
      basedOn: [
        "activityLevel",
        "fitnessGoal",
        "fitnessLevel",
        "trainingFrequency",
      ],
    },
  };
}

/**
 * Generate Steps Target - Strategy 2: AI-Personalized
 * Uses AI to personalize the recommendation with context
 */
export async function agentSteps(
  options: StepsGenerationOptions
): Promise<StepsGenerationResult> {
  const { questionnaireData, workoutProgram, onProgress } = options;

  // Calculate baseline using our logic
  const calculatedTarget = generateStepsTargetCalculated(options);

  try {
    // Use AI to personalize and provide better reasoning
    const systemPrompt = `
You are a fitness activity specialist creating personalized daily steps targets.

STEPS SCIENCE:
- General health: 7,000-10,000 steps/day
- Weight loss: 10,000-15,000 steps/day
- Maintenance: 8,000-10,000 steps/day
- Muscle building: 7,000-9,000 steps/day (preserve energy for lifting)

USER PROFILE:
- Activity Level: ${questionnaireData?.currentState?.dailyActivityLevel || "lightly-active"}
- Fitness Goal: ${questionnaireData?.wish?.fitnessGoal || "keep-fit"}
- Fitness Level: ${questionnaireData?.currentState?.fitnessLevel || "intermediate"}
- Training Frequency: ${questionnaireData?.accessibility?.trainingFrequency || 4} days/week
- Training Duration: ${questionnaireData?.accessibility?.trainingDuration || 60} minutes/session

${
  workoutProgram
    ? `TRAINING PROGRAM:
- Total Weeks: ${workoutProgram.weeks.length}
- Activities: ${Array.from(new Set(workoutProgram.weeks.flatMap((w) => w.days.map((d) => d.activityType)))).join(", ")}
- This is an active training program that will burn calories during workouts`
    : ""
}

BASELINE CALCULATION (from our algorithm):
- Daily Steps Goal: ${calculatedTarget.target.baseline.dailyStepsGoal}
${calculatedTarget.target.dailyAdjustments ? `- Daily Adjustments: ${calculatedTarget.target.dailyAdjustments.length} day-specific targets` : "- No daily adjustments (no workout program)"}

TASK:
Generate a personalized steps target with baseline and day-specific adjustments if a training program exists.
- Minimum: 5,000 steps
- Maximum: 20,000 steps
- Adjustments should make sense for the user's profile

Provide clear reasoning that connects to their specific situation and practical tips they can follow.
`;

    const result = await generateObject({
      model: openai("gpt-5-mini"),
      system: systemPrompt,
      prompt: "Generate my personalized daily steps target",
      schema: StepsTargetSchemaForAI,
      experimental_telemetry: {
        isEnabled: true,
        functionId: "steps-target",
      },
    });

    const aiOutput = result.object;
    const usage = result.usage;

    // Add weeklyTarget (not generated by AI to avoid null issues)
    const generatedTarget: StepsTarget = {
      ...aiOutput,
      baseline: {
        ...aiOutput.baseline,
        weeklyTarget: aiOutput.baseline.dailyStepsGoal * 7,
      },
    };

    // ✅ Send complete steps target to client
    if (onProgress) {
      onProgress({
        type: "steps-generated",
        steps: generatedTarget,
        currentComponent: "steps",
        status: "done",
      });
    }

    return {
      target: generatedTarget,
      metadata: {
        calculationMethod: "ai-personalized",
        basedOn: [
          "activityLevel",
          "fitnessGoal",
          "fitnessLevel",
          "trainingFrequency",
          "workoutProgram",
        ],
        usage, // Pass full usage object (RunLogger will normalize)
      },
    };
  } catch (error) {
    console.error(
      "[Steps Agent] AI generation failed, using calculated fallback:",
      error
    );
    // Return calculated fallback on error
    return calculatedTarget;
  }
}

/**
 * Validate questionnaire data before generation
 */
export function validateQuestionnaireData(questionnaireData: any): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  if (!questionnaireData) {
    errors.push("Questionnaire data is required");
    return { valid: false, errors };
  }

  // Optional validations - we have defaults for everything
  // Just warn if key data is missing
  if (!questionnaireData.currentState?.dailyActivityLevel) {
    console.warn(
      "[Steps Agent] Daily activity level not provided, using default"
    );
  }

  if (!questionnaireData.wish?.fitnessGoal) {
    console.warn("[Steps Agent] Fitness goal not provided, using default");
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}
